Add API to get secrets/variables
humanmade/altis-core pull request #1047
Opened 2024-05-27 16:00 UTC by rmccue

Fixes #1041.

2024-05-29 10:52 UTC, mikelittle requested changes
Just a doc block change to match the param removal.

2024-05-29 10:52 UTC, mikelittle commented on inc/namespace.php
> + * @param mixed $default Default value to return if not set (such as in local environments).
This `@param` doc needs removing now the parameter has been removed.
```suggestion
```

2024-06-17 10:32 UTC, kovshenin approved these changes

2024-06-17 10:54 UTC, mikelittle approved these changes

2024-06-17 11:35 UTC, merged